config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :products
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/option.rb
class Option < ApplicationRecord
  has_many :variant_options, dependent: :destroy
  has_many :variants, through: :variant_options

  validates :option_type, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :product_type
  belongs_to :user
  has_many :variants, dependent: :destroy
  accepts_nested_attributes_for :variants

  scope :most_recent, -> { order(created_at: :desc) }
  
  validates :sku, uniqueness: true
end

app/models/product_option.rb
class ProductOption < ApplicationRecord
  belongs_to :product_type

  validates :supported_option_type, uniqueness: true
end

app/models/product_type.rb
class ProductType < ApplicationRecord
  has_many :products, dependent: :destroy
  has_many :product_options, dependent: :destroy

  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  validates :name, presence: true, length: { maximum: 10 } 
  validates :email, uniqueness: true
  validates :password, presence: true, confirmation: true
  validates :contact, presence: true, length: { maximum: 10 }

  has_many :products
end

app/models/variant.rb
class Variant < ApplicationRecord
  belongs_to :product

  has_many :variant_options, dependent: :destroy
  has_many :options, through: :variant_options
  accepts_nested_attributes_for :options

  validates :sku, uniqueness: true
end

app/models/variant_option.rb
class VariantOption < ApplicationRecord
  belongs_to :option
  belongs_to :variant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :add_variant_to_product, only: :update
  before_action :add_options_to_variant, only: :update

  def index
    @products ||= Product.all.most_recent
  end
  
  def new
    @product = Product.new
  end

  def create
    if current_user.admin?
      @product = current_user.products.new(product_params)

      redirect_to products_path, notice: t('product.created') if @product.save
      flash.now[:alert] = t('product.not_created')
    else
      redirect_to root_path, alert: t('access_denied')
    end
  end

  def show
  end

  def edit
    @product.variants.all
    @supported_option_types = @product.product_type&.product_options.collect(&:supported_option_type)
    @options = Option.where(option_type: @supported_option_types)
  end

  def update
    @product.update(product_params) ? (render 'show') : (render 'edit')
  end

  def destroy
    @product.destroy
    redirect_to products_path, notice: t('product.deleted!')
  end
  
  private

  def product_params
    params.require(:product).permit(:title, :description, :sku, :product_type_id, 
                                    variants_attributes: [:id, :sku, :price, :quantity])
  end

  def set_product
    @product = Product.find(params.dig(:id))
  end

  def add_variant_to_product
    @variant = {}
    @variant.merge!(product_params.dig(:variants_attributes, '0'))
  end

  def add_options_to_variant
    @options = params.dig(:product, :options)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render "new"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :contact, :email, :password, :password_confirmation, :role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <h1><%= t('welcome') %></h1><br>
    <h3><%= t('admin_panel') %></h3><br>
    <p><%= link_to t('show_product'), products_path %></p><br>
    <p><%= link_to t('create_product'), new_product_path %></p><br>
    <p><%= link_to t('sign_out'), destroy_user_session_path, method: :delete %></p><br>
  <% else %>
    <h1><%= t('welcome') %> <%= current_user.name %></h1><br>
    <p><%= link_to t('show_product'), products_path %></p><br>
    <p><%= link_to t('sign_out'), destroy_user_session_path, method: :delete %></p><br>
  <% end %>
<% else %>
  <h1><%= t('welcome') %></h1><br>
  <p><%= link_to t('show_product'), new_user_registration_path %><br>
  <p><%= link_to t('sign_in'), new_user_session_path %><br>
<% end %>







































<%
=begin%>
 <h3>Welcome</h3>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <h3>Admin</h3>
    <p><%= link_to 'User count:', users_path %> <%= User.count %></p>
  <% else %>
    <h3>You've signed up. <%= link_to 'Download a free book', thankyou_path %></h3>
  <% end %>
<% else %>
  <h3>Sign up and download a free book.</h3>
  <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-primary btn-large' %>
<% end %> 
<%
=end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>SellarChamp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</body>

</html>

app/views/options/_option_fields.html.erb
<p>
  <%= of.label :option_type %><br>
  <%= of.select :option_type, options_for_select(@supported_option_types) %>
</p>

<p>
  <%= of.label :option_value %><br>
  <%= of.select :option_value, options_for_select(@options.collect(&:option_value).flatten) %>
</p>

app/views/products/_form.html.erb
<%= form_for @product  do |form| %>
  <% if @product.errors.any? %>
    <h2>
      <%= pluralize(@product.errors.count, "error") %> prohibited
      from creating the product!:
    </h2>
    <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :sku %><br>
    <%= form.text_field :sku %>
  </p>

  <p>
    <%= form.label :product_type %><br>
    <%= form.collection_select :product_type_id, ProductType.all, :id, :name %>
  </p>

  <p>
    <%= form.submit :ADDPRODUCT %><br>
  </p>
<% end %>
  

app/views/products/_heading.html.erb
<th><%= t('product.title') %></th>
<th><%= t('product.desc') %></th>
<th><%= t('product.sku') %></th>
<th><%= t('product.type') %></th>
<th><%= t('variant.sku') %></th>
<th><%= t('variant.price') %></th>
<th><%= t('variant.quantity') %></th>

app/views/products/_product_heading.html.erb
<tr>
  <%= render 'heading' %>
  <% unless current_user.admin? %>
    <th><%= t('option.type') %>/th>
    <th><%= t('option.value') %></th>
  <% end %>
</tr>

app/views/products/edit.html.erb
<h1><%= t('product.add_variations') %></h1>

<%= form_for @product do |form| %>
  <% if @product.errors.any? %>
    <div id= "error_explanation"> 
      <h2>
        <%= pluralize(@product.errors.count, "error") %> prohibited
        from creating the product!:
      </h2>
      <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id= "field">
    <p>
      <%= form.label :title %><br>
      <%= form.text_field :title %>
    </p>
  </div>

  <div id= "field">
    <p>
      <%= form.label :description %><br>
      <%= form.text_area :description %>
    </p>
  </div>

  <div id= "field">
    <p>
      <%= form.label :sku %><br>
      <%= form.text_field :sku %>
    </p>
  </div>

  <div id= "field">
    <p>
      <%= form.label :product_type %><br>
      <%= form.collection_select :product_type_id, ProductType.all, :id, :name %>
    </p>
  </div>

  <p><b><%= t('product.add_variant') %></b></p>

  <div id= "field">
    <%= form.fields_for :variants do |vf| %>
      
      <%= render 'variants/variant_fields', vf: vf %>

    <% end %>
  </div>

  <p><b><%= t('variant.add_option') %></b></p>

  <div id= "field">
    <%= form.fields_for :options do |of| %>
      
      <%= render 'options/option_fields', of: of %>

    <% end %>
  </div>

  <div id= "actions">
    <p>
      <%= form.submit :SaveProduct %><br>
    </p>
  </div>
  
<% end %>

app/views/products/index.html.erb
<h1><%= t('product.catalog') %></h1><br>
<% if @products.any? %>
  <table border= '1'>
    <tr>
      <%= render "heading" %>
    </tr>
    
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.description %></td>
        <td><%= product.sku %></td>
        <td><%= product.product_type.name %></td>
        <td><%= product.variants.collect(&:sku) %></td>
        <td><%= product.variants.collect(&:price) %></td>
        <td><%= product.variants.collect(&:quantity) %></td>

        <% unless current_user.admin? %>
          <td><%= link_to t('product.customize'), edit_product_path(product) %></td>
        <% else %>
          <td><%= link_to t('product.show'), product_path(product) %></td>
          <td><%= link_to t('product.delete'), product_path(product), method: :delete, data: { confirm: t('confirm') } %></td>
        <% end %>
      </tr>
    <% end %>

  </table>
<% else %>
  <h3><%= t('product.not_found') %></h3>
<% end %>

<% if current_user.admin? %>
  <br><td><%= link_to t('product.created'), new_product_path %></td>
<% end %>

<br><br><%= link_to t('home_page'), root_path %>

app/views/products/new.html.erb
<h1>Add Product</h1>

<%= render 'form' %>

<%= link_to t('products'), products_path %>

app/views/products/show.html.erb
<h1>Product <%= @product.id %></h1>

<table border= '1'>
  <%= render "product_heading" %>
  <tr>
    <td><%= @product.title %></td>
    <td><%= @product.description %></td>
    <td><%= @product.sku %></td>
    <td><%= @product.product_type.name %></td>
    <% unless current_user.admin? %>
      <td><%= @variant['sku'] %></td>
      <td><%= @variant['price'] %></td>
      <td><%= @variant['quantity'] %></td>
      <td><%= @options['option_type'] %></td>
      <td><%= @options['option_value'] %></td>
    <% else %>
      <td><%= @product.variants.collect(&:sku) %>
      <td><%= @product.variants.collect(&:price) %>
      <td><%= @product.variants.collect(&:quantity) %>
    <% end %>

  </tr>
</table>

<br><br><%= link_to t('product.catalog'), products_path %>

app/views/variants/_variant_fields.html.erb
<p>
  <%= vf.label :sku %><br>
  <%= vf.select :sku, options_for_select(@product.variants.collect(&:sku)) %>
</p>

<p>
  <%= vf.label :price %><br>
  <%= vf.select :price, options_for_select(@product.variants.collect(&:price)) %>
</p>

<p>
  <%= vf.label :quantity %><br>
  <%= vf.select :quantity, options_for_select(@product.variants.collect(&:quantity)) %>
</p>